on:
  push:
    branches: master
  schedule:
  - cron: "15 12 * * *"

name: update-data

jobs:
  render:
    name: update-data
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown, remotes, and the local package
        run: |
          install.packages("remotes")
          remotes::install_local(".")
          remotes::install_cran("tidyverse")
          remotes::install_cran("usethis")
          remotes::install_cran("readr")
        shell: Rscript {0}
      - name: Execute Script
        run: |
          Rscript -e 'library(tidyverse); mananciais <- mananciais:::obter_ano(ano = 2020, download_local = FALSE) %>%  mananciais:::limpar_dados(df = ., usar_baixados = FALSE, salvar_local = FALSE) %>% rbind(mananciais::mananciais_consolidado) ; usethis::use_data(mananciais, overwrite = T) ; readr::write_csv2(mananciais, "docs/data/mananciais.csv")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/mananciais.rda
          git add docs/data/mananciais.csv
          git commit -m 'Update data' || echo "Update data"
          git push origin || echo "Update data"
