on:
  push:
    branches: master

name: update-data

jobs:
  render:
    name: update-data
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown, remotes, and the local package
        run: |
          install.packages("remotes")
          remotes::install_local(".")
        shell: Rscript {0}
      - name: Execute Script
        run: |
          Rscript -e 'mananciais <- mananciais:::obter_ano(ano = 2020, download_local = FALSE) %>%  mananciais:::limpar_dados(df = ., usar_baixados = FALSE, salvar_local = FALSE) %>% rbind(mananciais::mananciais_consolidado)'
          Rscript -e 'usethis::use_data(mananciais, overwrite = T)'
          Rscript -e 'readr::write_csv2(mananciais, "docs/data/mananciais.csv")'
'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit README.md -m 'Script to update data' || echo "Script to update data"
          git push origin || echo "Script to update data"
